// <auto-generated />
using System;
using ApiPokemon.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ApiPokemon.Migrations
{
    [DbContext(typeof(PokemonContext))]
    partial class PokemonContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseCollation("SQL_Latin1_General_CP1_CI_AS")
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Proxies:ChangeTracking", false)
                .HasAnnotation("Proxies:CheckEquality", false)
                .HasAnnotation("Proxies:LazyLoading", true)
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AbilityPokemon", b =>
                {
                    b.Property<int>("IDpoke")
                        .HasColumnType("int");

                    b.Property<int>("IDability")
                        .HasColumnType("int");

                    b.HasKey("IDpoke", "IDability");

                    b.HasIndex("IDability");

                    b.ToTable("poke-ability", (string)null);
                });

            modelBuilder.Entity("ApiPokemon.Models.Ability", b =>
                {
                    b.Property<int>("Idability")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("IDability");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Idability"));

                    b.Property<string>("Abilityname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("abilityname");

                    b.HasKey("Idability");

                    b.ToTable("Abilities");
                });

            modelBuilder.Entity("ApiPokemon.Models.Category", b =>
                {
                    b.Property<int>("Idcat")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("IDcat");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Idcat"));

                    b.Property<string>("Category1")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("category");

                    b.HasKey("Idcat");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("ApiPokemon.Models.Egggroup", b =>
                {
                    b.Property<int>("Idegg")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("IDegg");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Idegg"));

                    b.Property<string>("Eggname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("eggname");

                    b.HasKey("Idegg");

                    b.ToTable("Egggroups");
                });

            modelBuilder.Entity("ApiPokemon.Models.Move", b =>
                {
                    b.Property<int>("Idmove")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("IDmove");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Idmove"));

                    b.Property<byte?>("Accuracy")
                        .HasColumnType("tinyint")
                        .HasColumnName("accuracy");

                    b.Property<int>("CatID")
                        .HasColumnType("int")
                        .HasColumnName("IDcat");

                    b.Property<string>("Movename")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("movename");

                    b.Property<byte?>("Power")
                        .HasColumnType("tinyint")
                        .HasColumnName("power");

                    b.Property<byte?>("Pp")
                        .HasColumnType("tinyint")
                        .HasColumnName("PP");

                    b.Property<int>("TypeID")
                        .HasColumnType("int")
                        .HasColumnName("IDtype");

                    b.HasKey("Idmove");

                    b.HasIndex(new[] { "CatID" }, "fk_moves_cat");

                    b.HasIndex(new[] { "TypeID" }, "fk_moves_type");

                    b.HasIndex(new[] { "Movename" }, "movename")
                        .IsUnique();

                    b.ToTable("Moves");
                });

            modelBuilder.Entity("ApiPokemon.Models.PokeType", b =>
                {
                    b.Property<int>("Idtype")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("IDtype");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Idtype"));

                    b.Property<string>("Typename")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("typename");

                    b.HasKey("Idtype");

                    b.ToTable("Types");
                });

            modelBuilder.Entity("ApiPokemon.Models.Pokemon", b =>
                {
                    b.Property<int>("Idpoke")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("IDpoke");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Idpoke"));

                    b.Property<byte>("Attack")
                        .HasColumnType("tinyint")
                        .HasColumnName("attack");

                    b.Property<byte>("Defense")
                        .HasColumnType("tinyint")
                        .HasColumnName("defense");

                    b.Property<bool>("Dualtype")
                        .HasColumnType("bit")
                        .HasColumnName("dualtype");

                    b.Property<byte>("Hp")
                        .HasColumnType("tinyint")
                        .HasColumnName("HP");

                    b.Property<string>("PicURL")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("PicURL");

                    b.Property<string>("Pokename")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("pokename");

                    b.Property<byte>("Spattack")
                        .HasColumnType("tinyint")
                        .HasColumnName("spattack");

                    b.Property<byte>("Spdefense")
                        .HasColumnType("tinyint")
                        .HasColumnName("spdefense");

                    b.Property<byte>("Speed")
                        .HasColumnType("tinyint")
                        .HasColumnName("speed");

                    b.HasKey("Idpoke");

                    b.HasIndex(new[] { "Pokename" }, "pokename")
                        .IsUnique();

                    b.ToTable("Pokemons");
                });

            modelBuilder.Entity("EgggroupPokemon", b =>
                {
                    b.Property<int>("IDpoke")
                        .HasColumnType("int");

                    b.Property<int>("IDegg")
                        .HasColumnType("int");

                    b.HasKey("IDpoke", "IDegg");

                    b.HasIndex("IDegg");

                    b.ToTable("poke-egg", (string)null);
                });

            modelBuilder.Entity("MovePokemon", b =>
                {
                    b.Property<int>("IDpoke")
                        .HasColumnType("int");

                    b.Property<int>("IDmove")
                        .HasColumnType("int");

                    b.HasKey("IDpoke", "IDmove");

                    b.HasIndex("IDmove");

                    b.ToTable("poke-move", (string)null);
                });

            modelBuilder.Entity("PokeTypePokemon", b =>
                {
                    b.Property<int>("IDpoke")
                        .HasColumnType("int");

                    b.Property<int>("IDtype")
                        .HasColumnType("int");

                    b.HasKey("IDpoke", "IDtype");

                    b.HasIndex("IDtype");

                    b.ToTable("poke-type", (string)null);
                });

            modelBuilder.Entity("AbilityPokemon", b =>
                {
                    b.HasOne("ApiPokemon.Models.Ability", null)
                        .WithMany()
                        .HasForeignKey("IDability")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ApiPokemon.Models.Pokemon", null)
                        .WithMany()
                        .HasForeignKey("IDpoke")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ApiPokemon.Models.Move", b =>
                {
                    b.HasOne("ApiPokemon.Models.Category", "CatNavigation")
                        .WithMany("Moves")
                        .HasForeignKey("CatID")
                        .IsRequired()
                        .HasConstraintName("fk_moves_cat");

                    b.HasOne("ApiPokemon.Models.PokeType", "TypeNavigation")
                        .WithMany("Moves")
                        .HasForeignKey("TypeID")
                        .IsRequired()
                        .HasConstraintName("fk_moves_type");

                    b.Navigation("CatNavigation");

                    b.Navigation("TypeNavigation");
                });

            modelBuilder.Entity("EgggroupPokemon", b =>
                {
                    b.HasOne("ApiPokemon.Models.Egggroup", null)
                        .WithMany()
                        .HasForeignKey("IDegg")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ApiPokemon.Models.Pokemon", null)
                        .WithMany()
                        .HasForeignKey("IDpoke")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MovePokemon", b =>
                {
                    b.HasOne("ApiPokemon.Models.Move", null)
                        .WithMany()
                        .HasForeignKey("IDmove")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ApiPokemon.Models.Pokemon", null)
                        .WithMany()
                        .HasForeignKey("IDpoke")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PokeTypePokemon", b =>
                {
                    b.HasOne("ApiPokemon.Models.Pokemon", null)
                        .WithMany()
                        .HasForeignKey("IDpoke")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ApiPokemon.Models.PokeType", null)
                        .WithMany()
                        .HasForeignKey("IDtype")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ApiPokemon.Models.Category", b =>
                {
                    b.Navigation("Moves");
                });

            modelBuilder.Entity("ApiPokemon.Models.PokeType", b =>
                {
                    b.Navigation("Moves");
                });
#pragma warning restore 612, 618
        }
    }
}
